### ISSUE TITLE
`toSendToast` failure fails all subsequent tests

### ISSUE THREAD

**Issue by romanmendez** [epicweb-dev/full-stack-testing#21]
When intentionally causing the `toSendToast` assertion to fail, Vitest will throw an `Unhandled Error` causing all subsequent tests to fail:
```
Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.
```

**Comment by kentcdodds** [comment]
I could not reproduce this.

<img width="1633" alt="image" src="https://github.com/epicweb-dev/full-stack-testing/assets/1500684/aacacfcc-0643-450b-bd8b-cff2be33eba8">

To try and reproduce this I made an intentional typo in one of the assertions and it failed as expected without affecting the other tests. I did this with http://localhost:5639/11/01/problem as my basis.

Did I miss something?

**Comment by romanmendez** [comment]
You're right. I had been able to reproduce it in the playground but I can't anymore. The issue in my version of the app was that I wasn't awaiting the custom assertion 😅. Thanks for looking at it and sorry for wasting your time.

**Comment by kentcdodds** [comment]
Oh it's not a waste! You're learning and so am I!
